### ISSUE TITLE
案件実績入力画面/デザイン作成

### ISSUE THREAD

**Issue by RyosukeSakakibara718** [RyosukeSakakibara718/project-balancer#131]
- 日毎
  - https://www.figma.com/design/nVVtG6m7amRrLpqIQMu5MX/project-balancer?node-id=549-4690&t=xToOc4Pl2lBYMBWx-1

![Image](https://github.com/user-attachments/assets/43de425a-c7da-420c-96ad-a58f56032841)

- 週毎
  - https://www.figma.com/design/nVVtG6m7amRrLpqIQMu5MX/project-balancer?node-id=611-576&t=xToOc4Pl2lBYMBWx-1

![Image](https://github.com/user-attachments/assets/a2a0564b-4236-40c8-9808-210dcf0ff033)

- 月毎
  - https://www.figma.com/design/nVVtG6m7amRrLpqIQMu5MX/project-balancer?node-id=611-3832&t=xToOc4Pl2lBYMBWx-1

![Image](https://github.com/user-attachments/assets/0043f204-dcf8-4b23-afa6-d96d35014a23)

**Comment by yokohama-TN** [comment]
@RyosukeSakakibara718 
整合性取れなくなるので、日毎以外の入力は受け付けない形にして欲しいです！

**Comment by RyosukeSakakibara718** [comment]
対応済みです！
