### ISSUE TITLE
【#40完了後】案件実績入力画面 / バックエンド実装 / セットアップ

### ISSUE THREAD

**Issue by yokohama-TN** [RyosukeSakakibara718/project-balancer#151]
- [ ] routeの作成
- [ ] Requestの作成
- [ ] Resourceの作成
- [ ] #153

**Comment by RyosukeSakakibara718** [comment]
[feature/#151](https://github.com/RyosukeSakakibara718/project-balancer/tree/feature/%23151)にて対応済み
