### ISSUE TITLE
メンバー管理画面 / API作成

### ISSUE THREAD

**Issue by RyosukeSakakibara718** [RyosukeSakakibara718/project-balancer#19]
- API
    - ~~メンバー情報登録~~
    - メンバー情報一覧取得
      - ~~検索機能を実装~~ -> テスト未実装
      - ~~ページネーションを実装~~ -> テスト未実装
    - ~~メンバー情報詳細取得~~
    - メンバー情報編集
      - [x] #56 
    - メンバー情報削除
      - [x] #57 
      - 残タスク
          - [ ] ~~#116~~
          - [ ] ~~#117~~
          - [ ] ~~#118~~
          - [ ] ~~#119~~
          - [ ] ~~#120~~
          - [ ] ~~#121~~

**Comment by yokohama-TN** [comment]
予定コマンド
`php artisan make:model Member -crR`

**Comment by yokohama-TN** [comment]
https://github.com/nshiro/faker-summary

**Comment by yokohama-TN** [comment]
通常DB用コマンド
`php artisan migrate:fresh --seed`

テストDB用コマンド
`php artisan migrate:fresh --seed  --env=testing`

**Comment by yokohama-TN** [comment]
Unit(単体テスト)はモックでテストしましょうってlaravelは言っている
(https://qiita.com/kawagashira/items/30b6fbd7a865f4005a90)

とは言ってもUnitでもモックをじゃなくてDBのデータでテストをすることもできる
今回はせっかくテスト用のDBも用意したのでUnitテストもDBのデータでテストしませんか？

**Comment by yokohama-TN** [comment]
コーディング規約追記事項
- messagesはフォームリクエストで定義
- バリデーションエラーハンドリングに関してもfailedValidationをオーバーライドして定義

**Comment by RyosukeSakakibara718** [comment]
https://qiita.com/ky0he1_sec/items/6cd8264f646bdf86cdb9

putでデータを処理したい場合の方法

```
edit () {
  const formData = new FormData()
  formData.appned('photo', this.photo)

  // ↓ POSTで送る
  axios.post(`/api/photos/${this.$route.params.photoId}`, formData, {
    // ↓ headersを追記
    headers: {
      'X-HTTP-Method-Override': 'PUT'
    }
  })
   .then(res => {
     console.log(res)
   })
   .catch(err => {
     console.log(err)
   })
}
```
