### ISSUE TITLE
要求をまとめる

### ISSUE THREAD

**Issue by RyosukeSakakibara718** [RyosukeSakakibara718/project-balancer#2]

**Comment by yokohama-TN** [comment]
# 要求定義

- 見積情報の

## 下記情報全て厳重管理
[開発会議資料_サンプル.xlsx](https://github.com/user-attachments/files/16201991/_.xlsx)

## サンプル内用語解説

### 請負収支報告
- 受注情報: 受注時の見積の金額/粗利率/工数(人月)を入力する
  - 受注額(引用): 見積時のクライアントへの請求額
  - 見積原価(計算): 見積時の原価額(メンバー等級原価×そのメンバーの工数(人月)=> (メンバー等級原価×そのメンバーの工数(人月))の合計)
  - 見積粗利額(計算): 見積時の粗利額(1- 見積原価/受注額)
  - 見積工数(計算): 見積時の工数(人月)の合計
  - 見積時間(計算): 見積工数×160 => 使用用途が不明
 
 - 着地見込
   - 粗利額(計算): 受注額から着地原価(予想)を引いたもの(受注額 - 着地原価(予想))
   - 着地原価(計算): 実績原価(現状かかっている原価)から予測した原価を表示(実績原価 + 残工数*平均単価*160*残工数) => ここの計算式は正確性にかなり欠けるので計算ロジックを変えたい
   - 予測工数(計算): 現状は実績工数と残工数を合計している(実績工数 + 残工数) => 予測としては全く機能していないので予測のロジックを考える必要がある
   - 予測時間(計算): 予測工数に160をかけたもの(予測工数×160) => 使用用途が不明
 - サマリ
   -  ◯月WEEK数字: 現在表示の週
   - 見積原価(引用): 見積時の◯月WEEK数字時点の原価を表示
   - 実績原価(引用): ◯月WEEK数字時点の原価の合計
   - 実績工数(引用): ◯月WEEK数字時点の工数の合計
   - 残工数(計算): 見積工数から実績工数を引いた(実績工数-見積工数)
   - 現在工程(入力): 作業フェーズ(要件定義/基本設計/詳細設計/製造/単体試験/結合試験/総合試験/リリース)
   - 現在契約(入力): 請負/準委任 => 要件定義と設計を準委任で行い、製造を請負にする契約形態があるから用意されている
   - 原価グラフ: 予定原価と実績原価のグラフ
     - Y軸: 金額 => 最大値は受注額の1.3倍ぐらいまで表示して欲しい
     - X軸: 期間 => 開始日から終わり+1ヶ月ぐらいを表示するようにしてほしい
     - 予定原価: 収支請負マスタで登録した月毎の見積原価でグラフを作成
     - 実績原価: 収支請負マスタで登録した月毎の実績原価までをグラフ化
- 期間(入力): 見積のスケジュールで登録した期間を表示
- 見積(入力): 見積のURLを表示 => 押下時は新規タブで表示
- WBS(入力): WBSのURLを表示 => 押下時は新規タブで表示
- コメント(入力): 報告用のコメント => 現状アーカイブが残らないので残るようにしてほしい
- メンバー(引用): メンバー名と等級を平均稼働を表示 => 現在の見かけとはかなり変えて欲しい => 下記に必要な項目を記載
  - メンバー毎の役職(PM/PL/PG/QA)と等級と単価と予定工数
  - 今月のメンバー毎の稼働と原価表示
- 累計: いらない

### 請負収支マスタ
- 等級原価: いらない
- PJコード: freeeのプロジェクトコード=>いらない
- 予実: 予定と実績
  - 見積工数(引用): 見積時のその月の工数の合計
  - 見積原価(引用): 見積時のその月の原価の合計
  - 見積人月(引用): その月の稼働開始から見積人月を週数で割った数値(見積工数/n週)
  - 見積積算原価(引用): その月の稼働開始から見積金額を週数で割った数値に全月までの積算金額を足した数値(見積原価/n週)
  - 実績積算時間(h) Freee工数手入力(引用): Freeeでメンバーが入力したその週の工数 => 積算という名前だが積算ではない
  - 実績積算原価(¥) Freee工数手入力(引用): Freeeで
