### ISSUE TITLE
larastan設定

### ISSUE THREAD

**Issue by RyosukeSakakibara718** [RyosukeSakakibara718/project-balancer#6]
対象ファイル：project-balancer/backend/laravel/app/Http/Controllers/Controller.php

1. `vendor/bin/phpstan analyse`を実行し、エラーが出ることを確認
2. 15行目をコメントアウト
3. 16行目のコメントアウトを外す
4. 26~29行目のコメントアウトを外す
5. `vendor/bin/phpstan analyse`を実行し、エラーが出ないを確認

**Comment by RyosukeSakakibara718** [comment]
PR：https://github.com/RyosukeSakakibara718/project-balancer/pull/7

**Comment by tks-yama** [comment]
検証方法記載してほしいです。

**Comment by RyosukeSakakibara718** [comment]
マージ済み
