### ISSUE TITLE
【テストコード作成】TableHeaderColumns.tsx

### ISSUE THREAD

**Issue by RyosukeSakakibara718** [RyosukeSakakibara718/project-balancer#76]

**Comment by tsukimi0618** [comment]
メモ

toHaveStyle は @testing-library/jest-dom パッケージに含まれているマッチャーです。しかし、vitest を使用している場合、デフォルトではこのマッチャーが含まれていないため、手動で追加する必要があります。

手順:
@testing-library/jest-dom をインストールする

まず、@testing-library/jest-dom パッケージをインストールします。

bash
コードをコピーする
npm install --save-dev @testing-library/jest-dom
セットアップファイルでjest-dom をインポートする

jest-dom を vitest に統合するために、setup ファイルを作成し、そこに @testing-library/jest-dom をインポートします。

例えば、setupTests.ts というファイルをプロジェクトの test フォルダや src フォルダに作成し、次のように書きます：

typescript
コードをコピーする
import '@testing-library/jest-dom';
vitest の設定に setupFiles を追加する

vitest の設定ファイル (vite.config.ts や vitest.config.ts など) に、セットアップファイルを指定します。

typescript
コードをコピーする
/// <reference types="vitest" />

import { defineConfig } from 'vite';

export default defineConfig({
  test: {
    setupFiles: './setupTests.ts',
  },
});
テストコードの修正

これで、@testing-library/jest-dom のマッチャーを使用できるようになります。

修正後のテストコード
typescript
コードをコピーする
import { render, screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import TableHeaderColumn from "../../../../src/components/atoms/column/TableHeaderColumn";
import React from "react";

// jest-domのマッチャーが利用可能になる
import '@testing-library/jest-dom';

describe('TableHeaderColumnコンポーネント', () => {

  it('widthプロパティが正しく適用されることを確認する', () => {
    const testWidth = "5%";
    render(<TableHeaderColumn width={testWidth}>ID</TableHeaderColumn>);
    const thElement = screen.getByText('ID');

    expect(thElement).toHaveStyle(`width: ${testWidth}`);
  });

  it('渡された子要素が正しくレンダリングされることを確認する', () => {
    render(<TableHeaderColumn>テストコンテンツ</TableHeaderColumn>);
    const thElement = screen.getByText('テストコンテンツ');
    
    expect(thElement).toBeInTheDocument();
    expect(thElement.tagName).toBe('TH'); // 確認するための追加チェック
  });

});
これで、toHaveStyle を使ったスタイルの検証が問題なく動作するはずです。

**Comment by tsukimi0618** [comment]
PR作成しました。
https://github.com/RyosukeSakakibara718/project-balancer/pull/98
